import os
from typing import Optional, Dict, Any
from openai import OpenAI
import requests
from utils.logger import get_logger

logger = get_logger(__name__)

def generate_response(
    prompt: str, 
    system_prompt: str = "You are a helpful AI assistant.", 
    provider: str = "openai", 
    api_key: Optional[str] = None, 
    model: str = "gpt-4o", 
    response_format: Optional[str] = None
) -> str:
    """
    Generates a response using either OpenAI or a local Ollama instance.

    Args:
        prompt (str): The user's input prompt.
        system_prompt (str, optional): The system prompt context. Defaults to "You are a helpful AI assistant.".
        provider (str, optional): The LLM provider ("openai" or "ollama"). Defaults to "openai".
        api_key (Optional[str], optional): The API key for OpenAI. Defaults to None.
        model (str, optional): The target model name. Defaults to "gpt-4o".
        response_format (Optional[str], optional): e.g. "json". Defaults to None.

    Returns:
        str: The text content generated by the language model.
    """
    logger.info(f"Generating LLM response. Provider='{provider}', Model='{model}'")
    
    if provider.lower() == "openai":
        if not api_key:
            logger.error("OpenAI API key missing.")
            return "Error: OpenAI API key is missing."
        
        try:
            client = OpenAI(api_key=api_key)
            kwargs: Dict[str, Any] = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ]
            }
            if response_format == "json":
                kwargs["response_format"] = {"type": "json_object"}

            response = client.chat.completions.create(**kwargs)
            logger.info("Successfully received OpenAI response.")
            return response.choices[0].message.content or ""
        except Exception as e:
            logger.error(f"OpenAI completion failed: {str(e)}", exc_info=True)
            return f"OpenAI Error: {str(e)}"
    
    elif provider.lower() == "ollama":
        base_url = os.getenv("OLLAMA_URL", "http://localhost:11434").rstrip("/")
        url = f"{base_url}/api/generate"
        
        # When using JSON, instruct Ollama explicitly via format option
        payload = {
            "model": model,
            "prompt": f"{system_prompt}\n\nUser: {prompt}",
            "stream": False
        }
        if response_format == "json":
            payload["format"] = "json"
            
        try:
            logger.debug(f"Sending request to Ollama URL: {url}")
            response = requests.post(url, json=payload, timeout=120)
            response.raise_for_status()
            logger.info("Successfully received Ollama response.")
            return response.json().get("response", "")
        except requests.exceptions.RequestException as e:
            logger.error(f"Ollama network/request error: {str(e)}", exc_info=True)
            return f"Ollama Error: {str(e)}"
        except Exception as e:
            logger.error(f"Ollama unexpected error: {str(e)}", exc_info=True)
            return f"Ollama Error: {str(e)}"
    
    logger.error(f"Unknown LLM provider specified: {provider}")
    return "Error: Unknown provider."
